### PR TITLE
Fixed issues with rotation

### PR DESCRIPTION
**Pull request by m-safan**
Issue 1: On opening the dialog in landscape mode, dialog appeared with extra 90 degree rotated.
Issue 2: Open dialog in potrait mode, now rotate the tablet, notice that some part of screen is accessible.

### CODE REVIEW

**Comment by alexsorokoletov** [comment]
@m-safan big thanks for your contribution! 😎 

@m-safan do you have screenshots how the issues 1 and 2 looked before the fix and after?
Would you be kind as to attach the screenshots and I'll be glad to merge

**Comment by m-safan** [comment]
**Issue1:**
Open date picker in landscape mode refer image

note the date picker is tilted by 90 degrees.

Image after fix.


**Issue 2:**
Open date picker in portrait mode refer image

Now rotate the tablet to landscape mode, 

notice some part of application is not hidden and is accessible.

Image after fix.

**Comment by m-safan** [comment]
@alexsorokoletov hope this helps.

**Comment by alexsorokoletov** [comment]
@m-safan, yes, thank you. 

Thank you for your contribution!

**Comment by m-safan** [comment]
@alexsorokoletov Thanks for taking my changes in.
Can I expect an NuGet update on this issue any time soon?

**Comment by alexsorokoletov** [comment]
@m-safan I'll do the update this week, thank you for your patience and contribution

**Comment by alexsorokoletov** [comment]
@m-safan it's on Nuget with version 1.0.2

**Pull request merged**
