### PR TITLE
added date range

### PR DESCRIPTION
**Pull request by nagarajas**
Made changes to accommodate date range in the calendar control. So with this pull request, we can restrict the date range for validation purpose.   

Example:
Here i have added date range from today to till tomorrow (day+1, i.e mindate: DateTime.Now - maxdate: DateTime.Now.AddDays(1))

### CODE REVIEW

**Comment by alexsorokoletov** [comment]
@nagarajas 
Thank you for submitting this pull request!

I would appreciate if you could:
- provide meaningful description to the pull request
- image/gif of the feature/changes you're bringing in
- format code changes (I think only this place is off https://github.com/alexsorokoletov/Xamarin.iOS.DatePickerDialog/pull/1/files#diff-015069d10750ee9a997e24b76b2321bbR34)

**Comment by nagarajas** [comment]
@alexsorokoletov I have made the changes and added description. Please do take a look into this.

**Comment by alexsorokoletov** [comment]
Very well, @nagarajas!
I still see that some of the code pieces are not formatted, make sure you format code once in a while or make it autoformat on save.
Will be less diffs in future commits in any of your projects.

Appreciate your contribution, @nagarajas!

**Comment by alexsorokoletov** [comment]
Updated package uploaded to NuGet.

**Pull request merged**
